services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  postgres:
    image: postgres:15
    container_name: postgresql
    hostname: postgresql
    environment:
      - POSTGRES_DB=mbankdb
      - POSTGRES_USER=mbank
      - POSTGRES_PASSWORD=mbank
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mbank -d mbankdb"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  api1:
    build:
      context: ../api-1
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: quarkus-api1
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/mbankdb
      - QUARKUS_DATASOURCE_USERNAME=mbank
      - QUARKUS_DATASOURCE_PASSWORD=mbank
      - QUARKUS_RABBITMQ_HOST=rabbitmq
      - QUARKUS_RABBITMQ_PORT=5672
      - QUARKUS_RABBITMQ_USERNAME=admin
      - QUARKUS_RABBITMQ_PASSWORD=password
      - QUARKUS_RABBITMQ_RECONNECT_ATTEMPTS=10
      - QUARKUS_RABBITMQ_RECONNECT_INTERVAL=2S
      - MP_MESSAGING_OUTGOING_FIPECHANNEL_CONNECTOR=smallrye-rabbitmq
      - MP_MESSAGING_OUTGOING_FIPECHANNEL_HOST=rabbitmq
      - MP_MESSAGING_OUTGOING_FIPECHANNEL_EXCHANGE_NAME=fipequeue
      - MP_MESSAGING_OUTGOING_FIPECHANNEL_QUEUE_NAME=fipequeue
    ports:
      - "8081:8080"
    networks:
      - app_network

  api2:
    build:
      context: ../api-2
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: quarkus-api2
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/mbankdb
      - QUARKUS_DATASOURCE_USERNAME=mbank
      - QUARKUS_DATASOURCE_PASSWORD=mbank
      - MP_MESSAGING_INCOMING_FIPECHANNEL_CONNECTOR=smallrye-rabbitmq
      - MP_MESSAGING_INCOMING_FIPECHANNEL_EXCHANGE_NAME=fipequeue
      - MP_MESSAGING_INCOMING_FIPECHANNEL_QUEUE_NAME=fipequeue
      - MP_MESSAGING_INCOMING_FIPECHANNEL_HOST=rabbitmq
      - QUARKUS_RABBITMQ_HOST=rabbitmq
      - QUARKUS_RABBITMQ_PORT=5672
      - QUARKUS_RABBITMQ_USERNAME=admin
      - QUARKUS_RABBITMQ_PASSWORD=password
      - QUARKUS_RABBITMQ_RECONNECT_ATTEMPTS=10
      - QUARKUS_RABBITMQ_RECONNECT_INTERVAL=2S
    ports:
      - "8082:8888"
    networks:
      - app_network

volumes:
  rabbitmq_data:
  rabbitmq_logs:
  postgres_data:

networks:
  app_network:
    driver: bridge